### PR TITLE
Standee design

### PR DESCRIPTION
**Pull request by tsl143**
Generic Mozilla standee

### CODE REVIEW

**Comment by barrosgeraldo** [comment]
I like this, but some improvements are needed in the style of text and spelling, we can do this after the merge.
Over this to @elioqoshi for check and ensure that it is aligned with guidelines.

**Comment by barrosgeraldo** [comment]
Hi @tsl143, thank you again for add this here.

1. Could you fix the object size that appears behind the text? Appears 2 times on the poster. I added the screenshots.
deepinscreenshot_select-area_20170804185444
deepinscreenshot_select-area_20170804185458

2. Do you have the source file (vector) for this poster?

**Comment by elioqoshi** [comment]
What blocks this here @barrosgeraldo

**Comment by barrosgeraldo** [comment]
I do not know if it's exactly an question, but need fixes before merge this. Ok?

**Comment by barrosgeraldo** [comment]
ping @tsl143

**Comment by tsl143** [comment]
@barrosgeraldo, Ohh, I missed this, my bad.
I am not the designer, I got this designed by some one (Read Faye :P)
here is the PSD link https://drive.google.com/open?id=0B7we3gC48gbdSnhhNzVpUW9fZXc

**Comment by barrosgeraldo** [comment]
ooops, @tsl143, I forgot something important, the Firefox logo changed and the [marketing language too](https://www.mozilla.org/en-US/firefox/?utm_medium=referral&utm_source=firefox-com), if you need a new banner open an issue and let's work on it. Let's consider push just updated design to avoid using old things.

**Pull request closed without merging**
