### PR TITLE
added Mozilla Support Logo

### PR DESCRIPTION
**Pull request by cynthiapereira**

### CODE REVIEW

**Comment by brwolfgang** [comment]
Nice logo!

**Comment by zilmarr** [comment]
It's beautiful!

**Comment by FabioBeneditto** [comment]
Nice ones :)

**Comment by elioqoshi** [comment]
This is different from the branding guidelines and also not official. Where has his been used as of now?

**Comment by cynthiapereira** [comment]
What is different from brand guidelines? The whole design or the icon? I agree that icon is outdated, should I send a version without the icon?

Yes, is not official or I do not needed to sent this one, right?! ;-)

Not yet used, but we really want to have a logo in our communications channels and in our events/activities.

**Comment by barrosgeraldo** [comment]
ping @elioqoshi

**Comment by cynthiapereira** [comment]
Since the [new guidelines for logo application](https://mozilla.ninja/expression/) have been updated, I am closed this PR.

**Pull request closed without merging**
