### PR TITLE
Restructuring the repo

### PR DESCRIPTION
**Pull request by kindavishal**
Solves https://github.com/mozilla/OpenDesign/issues/245

### CODE REVIEW

**Comment by kindavishal** [comment]
Hey @elioqoshi @pransh15 @AnXh3L0 @irvin @yofiesetiawan have a look here. Tried some housekeeping, the repo should look more manageable and easily accessible now!

**Comment by kindavishal** [comment]
What's new in this?
--
- Product/Project wise assets now lie in their own respective folders;
e.g. ```/Firefox, /A-Frame /Rust``` and so on
- All the Communities, i.e. their logos, banners, etc. now go under ```/Mozillians``` folder
- Campaigns run by Mozillians now have their own folders under ```/Campaigns```
- The year wise sorting still remains under ```Community Activites/<year>``` only for those assets which have date, venue, etc. on them. However, I considered campaigns such as "Rain of Rust", "Privacy Month" to NOT be region specific, which is why they go under ```/Campaigns```. Which in other words means that the year wise folders now only consists of smaller events/meetups run by various communities.
- There's a ```/Other Icons``` folder which consists of smaller yet may-be-useful logos that are relatable to Firefox and Mozilla.
e.g. The Tracking Protection icon, Web Developers Icons, etc.

While doing this, I found out quite a lot of assets which are available only in a single language, e.g. Spanish. I propose that we open Hackotoberfest Issues for new contributors to localize those graphics!

**Comment by irvin** [comment]
Seens good for me.

**Comment by irvin** [comment]
Seens good for me.

**Comment by yofiesetiawan** [comment]
Looks good, thank you Vishal!

**Comment by kindavishal** [comment]
Thank you for your feedback everyone! Merging this ✨

**Comment by pransh15** [comment]
This looks good, definitely gives us a clearer path to the assets and how well are they're placed. :)

**Pull request merged**
